
proxies:
- Hysteria2:
    name: 自用
    server: ''
    port: 23457
    auth: ''
    sni: aod.itunes.apple.com
    skip_tls_verify: true
policy_groups:
- select:
    name: myself
    policies:
    - 自用
    flatten: true
    icon: ''
rules:
- domain_regex:
    match: ^ad\..*|^ads\..*
    policy: REJECT
- rule_set:
    match: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    policy: REJECT
- rule_set:
    match: https://raw.githubusercontent.com/WuhanReganmian/app-config/main/blockList
    policy: REJECT
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list
    policy: DIRECT
- rule_set:
    match: https://raw.githubusercontent.com/WuhanReganmian/app-config/main/qx_direct_connections
    policy: DIRECT
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple_Domain.list
    policy: DIRECT
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list
    policy: myself    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list
    policy: myself
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list
    policy: myself
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list
    policy: myself    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list
    policy: myself
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list
    policy: myself
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list
    policy: myself
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list
    policy: DIRECT    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list
    policy: myself
- domain:
    match: ifconfig.me
    policy: DIRECT
- domain_suffix:
    match: cn
    policy: DIRECT
- geoip:
    match: CN
    policy: DIRECT
- ip_cidr:
    match: 192.168.0.0/16
    policy: DIRECT
- ip_cidr:
    match: 10.0.0.0/8
    policy: DIRECT
- ip_cidr:
    match: 127.0.0.0/8
    policy: DIRECT
- ip_cidr:
    match: 172.16.0.0/12
    policy: DIRECT
- ip_cidr:
    match: 192.128.0.0/16
    policy: DIRECT
- ip_cidr:
    match: 224.0.0.0/24
    policy: DIRECT
- default:
    policy: 所有节点
modules:
- name: BoxJs
  url: https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.surge.sgmodule
  enabled: true
- name: ScriptHub
  url: https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.surge.sgmodule
  enabled: true
- name: Sub-Store
  url: https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/config/Surge.sgmodule  
  enabled: true
- name: 'Spotify'
  url: https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.module
  enabled: true
- name: ''
  url: https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Enhance.sgmodule
  enabled: true
- name: '高德地图去广告'
  url: https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Module/NoAds/Amap.sgmodule
  enabled: true
- name: '滴滴出行去广告'
  url: https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Module/NoAds/Didichuxing.sgmodule
mitm:
  enabled: true
  ca_p12: egern.p12
  ca_passphrase: egern
